<a href="https://colab.research.google.com/github/KatyayaniNallajerla/Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

->NumPy is a Library

->NumPy does real good job on numerical operations

->NumPy only understand the numbers

->It is very useful library to perform mathematical and basic statistical operations

->It provides high performance multidimentional array

->NumPy is memory efficient

In [ ]:
import numpy as np


In [ ]:
l1=[1,5,4,3,2]
l1

[1, 5, 4, 3, 2]

In [ ]:
#CREATE THE ARRAY
#syntax
#np.array()

In [ ]:
array1=np.array(l1)
array1

array([1, 5, 4, 3, 2])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
print("Dimension of the Array is:" , array1.ndim)

Dimension of the Array is: 1


In [ ]:
print("Size of the Array is:" , array1.size) #it countsthe total  no.of elements in an arrya

Size of the Array is: 5


In [ ]:
print("Length of the Array is:",len(array1)) #length of array is

Length of the Array is: 5


In [ ]:
print("Data type of Arry elements is:", array1.dtype)

Data type of Arry elements is: int64


In [ ]:
print("Shape of the Array is:", array1.shape)

Shape of the Array is: (5,)


In [ ]:
array2=np.array([3.2,7.5,6.0,9.5])
array2

array([3.2, 7.5, 6. , 9.5])

In [ ]:
array2.ndim

1

In [ ]:
array2.size

4

In [ ]:
array2.dtype

dtype('float64')

In [ ]:
a3=np.array([1,2.3,3.2,4,6,8.1])
a3

array([1. , 2.3, 3.2, 4. , 6. , 8.1])

In [ ]:
a3.size

6

In [ ]:
a3.dtype

dtype('float64')

In [ ]:
a4=np.array([1,2.3,3.2,4,6,8.1],dtype='int') # change data type of array
a4

array([1, 2, 3, 4, 6, 8])

In [ ]:
a4.dtype

dtype('int64')

**2D Array**

In [ ]:
a2=np.array([[1,2,3,4,5]])
a2

array([[1, 2, 3, 4, 5]])

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
print("Dimension is:",a2.ndim)

Dimension is: 2


In [ ]:
a2.size

5

In [ ]:
a2.shape #rows, col

(1, 5)

In [ ]:
arry=np.array([[1,2,3],[4,5,6]])
arry

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arry.size

6

In [ ]:
arry.shape

(2, 3)

In [ ]:
arry.ndim

2

**3D Array**

In [ ]:
arry3d=np.array([[[1,2,3,4]]])
arry3d

array([[[1, 2, 3, 4]]])

In [ ]:
arry3d.shape


(1, 1, 4)

In [ ]:
arry3d.ndim

3

In [ ]:
arry3d.size

4

In [ ]:
arr=np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])
arr.shape


(1, 4, 3)

In [ ]:
arr.ndim

3

In [ ]:
arr=arr.flatten()#converting 3d to 1d
arr

array([1, 2, 3, 1, 2, 3, 3, 6, 7, 1, 2, 3, 1, 2, 3, 8, 9, 7, 5, 8, 9, 0,
       0, 0, 0, 0, 0])

1.Can we calculate the sum of array without loop in python

2.calculate the sum of array

3.with th ehelp of th eloop we need to pass the elements in an array 2D#user defined input for array